import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { getTableColumns, is, SQL } from 'drizzle-orm';
import { getTableConfig } from 'drizzle-orm/sqlite-core';
import type { SQLiteTableWithColumns } from 'drizzle-orm/sqlite-core';
import * as schema from '../src/db/schema.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = join(__dirname, '..', 'DATABASE_SCHEMA.md');

type TableExport = SQLiteTableWithColumns<Record<string, unknown>>;

const tables = Object.entries(schema)
  .filter(
    (entry): entry is [string, TableExport] => {
      const val = entry[1];
      return val !== null
        && typeof val === 'object'
        && Symbol.for('drizzle:IsDrizzleTable') in (val as object);
    },
  );

function getForeignKeyRef(fk: { foreignTableName: string; foreignColumns: { name: string }[] }): string {
  return `${fk.foreignTableName}(${fk.foreignColumns.map((c) => c.name)
    .join(', ')})`;
}

function formatMarkdownTable(headers: string[], rows: string[][]): string[] {
  const allRows = [headers, ...rows];
  const widths = headers.map((_, colIdx) =>
    Math.max(...allRows.map((row) => row[colIdx].length)),
  );

  const padCell = (val: string, width: number) => val.padEnd(width);
  const separator = `|${widths.map((w) => '-'.repeat(w + 2))
    .join('|')}|`;
  const headerLine = `| ${headers.map((h, i) => padCell(h, widths[i]))
    .join(' | ')} |`;
  const dataLines = rows.map(
    (row) => `| ${row.map((cell, i) => padCell(cell, widths[i]))
      .join(' | ')} |`,
  );

  return [headerLine, separator, ...dataLines];
}

const lines: string[] = [
  '<!-- AUTO-GENERATED by `npm run db:schema-doc` — do not edit manually -->',
  '',
  '# Database Schema',
  '',
  `Generated from \`src/db/schema.ts\`. Regenerate with:`,
  '',
  '```sh',
  'npm run db:schema-doc',
  '```',
  '',
];

for (const [exportName, table] of tables) {
  const config = getTableConfig(table);
  const columns = getTableColumns(table);

  lines.push(`## \`${config.name}\` (export: \`${exportName}\`)`);
  lines.push('');

  // Build FK lookup from table config
  const fkMap = new Map<string, string>();
  for (const fk of config.foreignKeys) {
    const fkConfig = fk.reference();
    for (let i = 0; i < fkConfig.columns.length; i++) {
      const col = fkConfig.columns[i];
      fkMap.set(col.name, getForeignKeyRef({
        foreignTableName: fkConfig.foreignTable[Symbol.for('drizzle:Name') as unknown as keyof typeof fkConfig.foreignTable] as string,
        foreignColumns: [fkConfig.foreignColumns[i]],
      }));
    }
  }

  const headers = ['TS Name', 'SQL Name', 'Type', 'Nullable', 'PK', 'Default', 'FK Reference'];
  const rows: string[][] = [];

  for (const [tsName, col] of Object.entries(columns)) {
    const sqlName = col.name;
    const colType = col.columnType;
    const nullable = col.notNull ? 'No' : 'Yes';
    const pk = col.primary ? 'Yes' : '';
    let defaultVal = '';
    if (col.hasDefault) {
      const d = col.default;
      if (d === undefined || d === null) {
        defaultVal = 'auto';
      } else if (is(d, SQL)) {
        const chunks = d.queryChunks as unknown[];
        const parts: string[] = [];
        for (const chunk of chunks) {
          if (typeof chunk === 'string') {
            parts.push(chunk);
          } else if (chunk && typeof chunk === 'object' && 'value' in (chunk as Record<string, unknown>)) {
            parts.push(String((chunk as { value: unknown }).value));
          }
        }
        defaultVal = parts.length > 0 ? `\`${parts.join('')}\`` : 'SQL';
      } else {
        defaultVal = String(d);
      }
    }
    const fkRef = fkMap.get(sqlName) ?? '';

    rows.push([tsName, sqlName, colType, nullable, pk, defaultVal, fkRef]);
  }

  lines.push(...formatMarkdownTable(headers, rows));
  lines.push('');
}

lines.push(`---`);
lines.push(`*${tables.length} tables total*`);
lines.push('');

writeFileSync(outputPath, lines.join('\n'));
console.log(`Wrote ${outputPath} (${tables.length} tables)`);
